#!/usr/bin/env Rscript

args = commandArgs(trailingOnly = TRUE)

library(rmarkdown)

input = args[1]
header = args[2]

tex_header = includes(in_header = header)
render(input, pdf_document(includes = tex_header, number_sections = TRUE, fig_caption = TRUE))
#render(input, c("html_document", "pdf_document"), number_sections = TRUE)
